# Generated by Django 5.0.3 on 2025-03-01 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('id_card', models.CharField(max_length=13, unique=True, verbose_name='รหัสบัตรประชาชน')),
                ('birth_date', models.DateField(verbose_name='วันเดือนปีเกิด')),
                ('gender', models.CharField(choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่นๆ')], max_length=10, verbose_name='เพศ')),
                ('weight', models.FloatField(verbose_name='น้ำหนัก (กก.)')),
                ('height', models.FloatField(verbose_name='ส่วนสูง (ซม.)')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทร')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่เช็คอิน')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='dogym.member', verbose_name='สมาชิก')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogym.staff', verbose_name='พนักงานที่เช็คอิน')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_added', models.PositiveIntegerField(verbose_name='จำนวนวันที่เพิ่ม')),
                ('paid_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่บันทึก')),
                ('expiry_date', models.DateTimeField(verbose_name='วันที่หมดอายุ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to='dogym.staff', verbose_name='ผู้บันทึกข้อมูล')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dogym.member', verbose_name='สมาชิก')),
            ],
        ),
    ]
