# Generated by Django 5.0.3 on 2025-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogym', '0002_alter_checkin_check_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
    ]
